# Generated by Django 3.1.2 on 2020-10-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
